baseURL: "http://akademi.eresbiotech.com/"
theme: "up-business-theme"
languageCode: "tr-tr"
markup:
  goldmark:
    renderer:
      unsafe: true
title: "Eres Biyoinformatik Akademi"

# googleAnalytics: ""
paginate: 20
summaryLength: 20

params:
  title: "Eres Biyoinformatik Akademi "
  description: "Eres Biyoteknoloji tarafindan ..."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://instagram.com/eresbiotech"
    facebook: "https://facebook.com/eresbiotech"
    twitter: "https://twitter.com/eresbiotech"

  location:
    - "Söğütözü Mahallesi Ssöğütözü Caddesi Ankara Koç İkiz Kuleleri, D:2/D No:34, 06000 Çankaya/Ankara"

  contact:
    - "info@eresbiotech.com"

  copyright: "© 2023 Eres Biotech"

menus:
  main:
    - name: "Anasayfa"
      url: "/#hero"
      weight: 1

    - name: "Hakkımızda"
      url: "/about"
      weight: 2

    - name: "Hizmetlerimiz"
      url: "/work"
      weight: 3

    - name: "Eğitimler"
      url: "/blog"
      weight: 5

  buttons:
    - name: "Iletisim"
      url: "/post/contact"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Anasayfa"
      url: "/#hero"
      weight: 1

    - name: "Hakkimizda"
      url: "/about"
      weight: 2

    - name: "Hizmetlerimiz"
      url: "/work"
      weight: 3


    - name: "Eğitimler"
      url: "/blog"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
