baseURL: "https://www.eresbiotech.com/"
languageCode: "tr-tr"
enableRobotsTXT: true
markup:
  goldmark:
    renderer:
      unsafe: true
title: "ERES Biyoteknoloji | Doğadan İlham Alan Strateji ve Çözüm Stüdyosu"

# googleAnalytics: ""
paginate: 20
summaryLength: 20

params:
  title: "ERES Biyoteknoloji"
  description: "ERES Biyoteknoloji; doğadan, yaşam bilimlerinden ve ekolojik sistemlerden ilham alan strateji, eğitim, sürdürülebilirlik ve çözüm geliştirme modelleri tasarlayan bilim temelli bir stüdyodur."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    instagram: "https://instagram.com/eresbiotech"
    facebook: "https://facebook.com/eresbiotech"
    twitter: "https://twitter.com/eresbiotech"

  location:
    - "Söğütözü Mahallesi Ssöğütözü Caddesi Ankara Koç İkiz Kuleleri, D:2/D No:34, 06000 Çankaya/Ankara"

  contact:
    - "info@eresbiotech.com"

  copyright: "© 2023 Eres Biotech"

menus:
  main:
    - name: "Anasayfa"
      url: "/"
      weight: 1

    - name: "Çözümler"
      url: "/#cozumler"
      weight: 2

    - name: "Strateji Stüdyosu"
      url: "/#strateji-studyosu"
      weight: 3

    - name: "NaturaLogic"
      url: "https://naturalogiclabs.com"
      weight: 4

    - name: "ERES Akademi"
      url: "https://akademi.eresbiotech.com"
      weight: 5

  buttons:
    - name: "İletişim"
      url: "/#iletisim"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Anasayfa"
      url: "/"
      weight: 1

    - name: "Çözümler"
      url: "/#cozumler"
      weight: 2

    - name: "NaturaLogic"
      url: "https://naturalogiclabs.com"
      weight: 3


    - name: "ERES Akademi"
      url: "https://akademi.eresbiotech.com"
      weight: 5

taxonomies:
  series: "series"
  tags: "tags"
